# Operator: When using the 'Exists' operator, you only need to specify the key.
# The toleration will match any taint with the specified key, regardless of its value.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: taint-tolerations
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
      tolerations:
      - key: "hello"
        operator: "Exists"  # This toleration matches any taint with key "hello" regardless of the value.
        effect: "NoSchedule"


# Operator: When using the 'Equal' operator, you must specify both the key and the value.
# The toleration will only match taints that have exactly the same key and value.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-equal-deployment
  labels:
    app: nginx-equal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-equal
  template:
    metadata:
      labels:
        app: nginx-equal
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
      tolerations:
        - key: "example-key"
          operator: "Equal"  # This toleration matches only taints with key "example-key" and value "example-value".
          value: "example-value"
          effect: "NoSchedule"
