apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: nginx   # This should match the labels of your pods
