apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-readonly-role-binding
subjects:
- kind: User
  name: aaqib-rbac # Replace with the username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dev-readonly-role
  apiGroup: rbac.authorization.k8s.io
  
